# Generated by Django 6.1.1 on 2026-09-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_low_confidence',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expiring_soon', 'Expiring soon'), ('expired', 'Expired'), ('used', 'Used')], db_index=True, default='active', max_length=20),
        ),
    ]
