# Generated by Django 6.1.1 on 2026-09-22 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sms', 'SMS'), ('gmail', 'Gmail')], max_length=10)),
                ('raw_ref', models.TextField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_messages', to='accounts.user')),
            ],
        ),
    ]
