# Generated by Django 6.1.1 on 2026-09-22 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token_encrypted', models.TextField()),
                ('refresh_token_encrypted', models.TextField()),
                ('token_expiry', models.DateTimeField()),
                ('scope', models.CharField(blank=True, max_length=255)),
                ('last_history_id', models.CharField(blank=True, max_length=64, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='sourcemessage',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='sourcemessage',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('user', 'source_type', 'external_id'), name='unique_user_source_external_id'),
        ),
        migrations.AddField(
            model_name='gmailcredential',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_credential', to='accounts.user'),
        ),
    ]
